spring:
  application:
    name: STM
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.2 # 응답의 창의성을 낮춰 일관된 결과를 유도


  # DataBase
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource

# mybatis sql ??
logging:
  level:
    com:
      sys:
        stm: debug

server:
  port: 8080

app:
  report:
    save-path: ./reports  # 기본값: 현재 디렉토리의 reports 폴더

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
  plugins:
    - com.sys.stm.global.common.interceptor.AuditingInterceptor


cloud:
  naver:
    clova:
      client: ${NAVER_CLIENT}
      secret: ${NAVER_SECRET}