spring:
  application:
    name: STM

  # DataBase
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: SCOTT
    password: TIGER
    type: com.zaxxer.hikari.HikariDataSource

# mybatis sql ??
logging:
  level:
    com:
      sys:
        stm: debug

server:
  port: 8080



mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
